### ISSUE TITLE
plugin code

### ISSUE THREAD

**Issue by ezavile** [ezavile/postcss-text-transform#3]
## Create a rule to transform the text
```css
.componentNameLowerFirst {
  @each $color in green, yellow, red {
    @textTransform $color, upperFirst, $colorTransformed {
      &--bg$(colorTransformed) {
        background-color: $color;
      }
    }
  }
}
```

## result:

```css
.componentNameUpperFirst--bgGreen {
   background-color: green
}

.componentNameUpperFirst--bgYellow {
   background-color: yellow
}

.componentNameUpperFirst--bgRed {
   background-color: red
}
```

## type of transformation:

- capitalize
- camelCase
- lowerFirst
- lowerCase
- upperCase
- upperFirst
